### ISSUE TITLE
Add a way to configure the registry for a `rancher2_cluster_v2` as to be used for Rancher System Images

### ISSUE THREAD

**Issue by izaac** [rancher/terraform-provider-rancher2#1048]
In `rancher2_cluster` resource `private_registries` makes the cluster pull the `Rancher System Images` from that/those registries by default.

Example:

```tf
resource "rancher2_cluster" "custom_cluster_rke1" {
  provider = rancher2.admin
  name = "custom-cluster-privreg-rke1"
  enable_cluster_monitoring = false
  rke_config {
    network {
      plugin = "canal"
    }
    private_registries {
      url = "${var.registry_auth_host}"
      user = "corral"
      password = "${var.password}"
      is_default = false
    }
    kubernetes_version = "${var.kubernetes_version_rke1}"
  }
}
```

In the `rancher2_cluster_v2` resource if registries are defined those are not used for `Rancher System Images` but for other chart images.

```tf
resource "rancher2_cluster_v2" "custom_cluster" {
  provider = rancher2.admin
  name = "custom-cluster-privreg1"
  kubernetes_version = "${var.kubernetes_version}"
  rke_config {
    registries {
      configs {
        hostname = "${var.registry_auth_host}"
        auth_config_secret_name = rancher2_secret_v2.registry_auth.name
        insecure = true
        tls_secret_name = ""
        ca_bundle = ""
      }
    }
  }
}
```

This is how the configuration looks like from the Rancher UI when provisioning. Note that it is contained in the `Configure advanced containerd mirroring and registry authentication options` section and the `Rancher System Images` field is empty when no `system-default-registry` in Rancher.

<img width="1204" alt="Screen Shot 2022-12-14 at 10 19 01 AM" src="https://user-images.githubusercontent.com/27659/207935240-4c2b2991-b466-46f5-b32b-6f58745edf85.png">

However this `Rancher System Images` registry hostname can be configured from the Rancher UI in these two sections:

- `Configure advanced containerd mirroring and registry authentication options`
- `Use specified private registry for Rancher System Container Images`

For the first one it can be observed in the screenshot above, the second option is in the following screen:

<img width="1091" alt="Screen Shot 2022-12-15 at 11 18 18 AM" src="https://user-images.githubusercontent.com/27659/207937282-58d0b4d6-5182-4ff5-a446-eaef34a2e857.png">

Configuring from the UI makes the RKE2 cluster provision with the System images pulled from the specified registry.

Expectation:

- Specify registry and a way to configure the cluster to pull the `Rancher System Images` too with Terraform (RKE2)

Actual Behavior:

- No way to configure the provisioned cluster to use the specified registry to pull the `Rancher System Images` using TF (RKE2)

Terraform Rancher Provider version `v1.25.0`
Rancher Version: `v2.7.0`

Cluster types:
- RKE2 Node Driver
- RKE2 Custom

**Comment by HarrisonWAffel** [comment]
When deploying RKE2 clusters Rancher will [look to the `MachineSelectorConfig` or the `MachineGlobalConfig` to determine the registry that should be used when pulling system images](https://github.com/rancher/rancher/blob/603b17ec3334841c9c7e6bd450bbc9f9c36353f1/pkg/provisioningv2/image/resolve.go#L63) (and if neither contain a registry, default to the global registry).

It's a bit unintuitive, but for Rancher to pull system-images from a private registry during initial provisioning both the `Registries` section of the `RKEConfig` _and_ the `MachineSelectorConfig`/`MachineGlobalConfig` need to contain registry information.

For example, when creating an RKE2 cluster with a private registry configured, the YAML will look like the following (irrelevant yaml fields have been omitted)

```yaml
spec:
...
  rkeConfig:
   ...
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
      profile: null
    ...
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
          system-default-registry: a-fake-registry-hostname
    registries:
      configs:
        a-fake-registry-hostname:
          authConfigSecretName: registryconfig-auth-phgmk
          insecureSkipVerify: false
        another-fake-registry-hostname:
          authConfigSecretName: registryconfig-auth-ntswz
          caBundle: ''
          insecureSkipVerify: false
        a-third-fake-registry-hostname:
          caBundle: ''
          insecureSkipVerify: false
      mirrors:
        {}
```

The `registries` section within the `rkeConfig` [mirrors the format of RKE2's `registries.yaml` file](https://docs.rke2.io/install/containerd_registry_configuration?_highlight=registries#registries-configuration-file), which allows users to pull images from particular registries without having to explicitly provide pull secrets. There may be many registries defined within this field, so in order for Rancher to know which one should be used as the default when pulling initial system-images the `system-default-registry` field within the `machineSelectorConfig` (or `machineGlobalConfig`) is referenced.  While RKE1 provided the `is-default` attribute within its `registries` list, RKE2 does not have a similar concept. 

I'm in the process of testing the current provider to ensure that the same configuration as seen in the above yaml works in terraform, and if so there may not be any code changes required but rather additional documentation to clarify this behavior.
