### ISSUE TITLE
[BUG] secrets_encryption_config.custom_config not working properly

### ISSUE THREAD

**Issue by jympetalmd** [rancher/terraform-provider-rancher2#1075]
### Rancher Server Setup
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1 1.23.10

### Information about the Cluster
- Kubernetes version: 1.23.14
- Cluster Type (Local/Downstream): Downstream (Custom) RKE1 on Azure

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? "= 1.25.0"
- What is the version of Terraform in use? "= 1.3.7"

### Describe the bug
My custom_config is configured like this:
```
      kube_api {
        pod_security_policy = false
        secrets_encryption_config {
          enabled       = true
          custom_config = <<-YAML
            apiVersion: apiserver.config.k8s.io/v1
            kind: EncryptionConfiguration
            resources:
            - resources:
              - secrets
              providers:
              - secretbox:
                  keys:
                  - name: key1
                    secret: ${base64encode(random_password.etcd_encryption_key.result)}
              - identity: {}
          YAML
        }
      }
```
1. The plan always shows a change on this when it should'nt:
```
              ~ kube_api {
                    # (9 unchanged attributes hidden)

                  ~ secrets_encryption_config {
                      ~ custom_config = (sensitive value)
                        # (1 unchanged attribute hidden)
                    }
                }
```
2. The cluster yaml (in UI) doesn't show the config:
```
      kubeApi:
        secretsEncryptionConfig:
          customConfig:
            apiVersion: apiserver.config.k8s.io/v1
            kind: EncryptionConfiguration
            resources: null
          enabled: true
````
3. The encryption file on the master is showing double headers
```
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- providers:
  - secretbox:
      keys:
      - name: key1
        secret: XXXXXXXXXXXXXX
  - identity: {}
  resources:
  - secrets
```
