### ISSUE TITLE
[Feature] Enable optional OS Selection

### ISSUE THREAD

**Issue by frank-at-suse** [rancher/terraform-provider-rancher2#1193]
### Is your feature request related to a problem? Please describe.
When creating an RKE2 cluster declaratively, a type of `machineOS` can be set:

```yaml
machinePools:
  - name: pool1
    etcdRole: false
    controlPlaneRole: false
    workerRole: true
    hostnamePrefix: ''
    quantity: 1
    unhealthyNodeTimeout: 0m
    machineConfigRef:
      kind: VmwarevsphereConfig
      name: nc-undefined-pool1-sv92k
    machineOS: windows
```

This is not currently available via rancher2 Terraform provider, causing new Windows cluster deployments to fail and additions of Windows machine pools to existing clusters not possible.

### Describe the solution you'd like
Enable `machineOS` as an optional machine_pool schema to allow creation of Windows Clusters/node pools.  There should also be a check/error handling to ensure that Windows pools can only be assigned the `worker` role.

### Describe alternatives you've considered
Manual registration of Windows worker nodes
