### ISSUE TITLE
[Problem] cluster grace period can't be set to unlimited

### ISSUE THREAD

**Issue by qaz-t** [rancher/terraform-provider-rancher2#1333]
### Rancher Server Setup
- Rancher version: `v2.7.9`
- Installation option (Docker install/Helm Chart): `Helm Chart`
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): `RKE2` `v1.26.15+rke2r1`
- Proxy/Cert Details:

### Information about the Cluster
- Kubernetes version: `v1.26.15+rke2r1`
- Cluster Type (Local/Downstream): `Downstream`
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): `Custom`

### User Information
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: `Admin`

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? `4.1.0`
- What is the version of Terraform in use? `1.7.4`

### Describe the bug

I defined a custom rke2 cluster using the following config:
```
resource "rancher2_cluster_v2" "custom_cluster" {
  name               = var.cluster_name
  kubernetes_version = var.kubernetes_version
  cluster_agent_deployment_customization {}
  fleet_agent_deployment_customization {}
  rke_config {
    chart_values          = <<EOF
rke2-cilium: {}
EOF
    machine_global_config = <<EOF
cni: "cilium"
disable-kube-proxy: false
etcd-expose-metrics: false
profile: null
EOF
    machine_selector_config {
      config = <<EOF
protect-kernel-defaults: false
system-default-registry: docker.io
EOF
    }
    upgrade_strategy {
      control_plane_concurrency = "1"
      control_plane_drain_options {
        delete_empty_dir_data                = true
        disable_eviction                     = false
        enabled                              = false
        force                                = false
        grace_period                         = -1
        ignore_daemon_sets                   = true
        ignore_errors                        = false
        skip_wait_for_delete_timeout_seconds = 0
        timeout                              = 120
      }
      worker_concurrency = "1"
      worker_drain_options {
        delete_empty_dir_data                = true
        disable_eviction                     = false
        enabled                              = true
        force                                = false
        grace_period                         = -1
        ignore_daemon_sets                   = true
        ignore_errors                        = false
        skip_wait_for_delete_timeout_seconds = 0
        timeout                              = 120
      }
    }
    etcd {
      snapshot_schedule_cron = "0 */5 * * *"
      snapshot_retention     = 5
    }
  }
}
```
Apply is complete, then I get the cluster yaml file in rancher UI, I got:

```
upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: 0
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: true
        force: false
        gracePeriod: 0
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
```
`gracePeriod` is `0` instead of `-1`

### To Reproduce

just apply the rancher2_cluster_v2 resource provide above.

### Actual Result

`gracePeriod` should be `-1` like I set in config ranther than 0

### Expected Result

in rancher cluster yaml file, `gracePeriod: -1` should be there

### Screenshots

![config](https://github.com/rancher/terraform-provider-rancher2/assets/55623789/feb6ff43-48e1-4c50-bbc2-fa1b6f2dbe76)
![apply](https://github.com/rancher/terraform-provider-rancher2/assets/55623789/8207dab3-4bdd-41db-b3d1-ad1de2d72cbc)
![result](https://github.com/rancher/terraform-provider-rancher2/assets/55623789/4e72b953-03a2-46b3-a4c2-15a4a83984e0)

### Additional context

If I directly create custom rke2 cluster in rancher UI, the gracePeriod value can be set to -1(default value is -1)
