### ISSUE TITLE
[BUG] rke2 machineSelectorFiles.fileSources have multiple duplicate entries

### ISSUE THREAD

**Issue by kinarashah** [rancher/terraform-provider-rancher2#1426]
### Rancher Server Setup
- Rancher version: v2.9.1

### Information about the Cluster
- Kubernetes version: Any
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster?  RKE2 Node driver cluster 

### Provider Information
- What is the version of the Rancher v2 Terraform Provider in use? Built locally off master commit - `8356b631d76f5fd69276906c405233571beb6bdc` 
- What is the version of Terraform in use? Terraform v1.9.8

### Describe the bug
1. The default value of `dynamic` field using terraform provider should be consistent with Rancher API. `dynamic` is false when editing cluster object using API/UI but set to `true` using terraform. 
2. Multiple duplicate entries for `fileSources` are added to the cluster object under `machineSelectorFiles`. Only one entry is expected for the same secret and hash value. 

### To Reproduce
- Provision a RKE2 node driver cluster using terraform, make sure to set   `default_pod_security_admission_configuration_template_name`. I set it to "rancher-restricted". 
- After the cluster is provisioned, edit `snapshot_retention` or any other cluster field to trigger cluster reconciliation. 
- Observe that a new entry is added to the cluster object: 
```
    - fileSources:
      - configMap:
          name: ""
        secret:
          items:
          - dynamic: true
            hash: LW5oTV9pmpX7+xWMjgC3IgbHtLkSMlCgyaKXG13CihA=
            key: admission-config-psact
            path: /etc/rancher/rke2/config/rancher-psact.yaml
          name: molmedocis-admission-configuration-psact
      machineLabelSelector:
        matchLabels:
          rke.cattle.io/control-plane-role: "true"
    - fileSources:
      - configMap:
          name: ""
        secret:
          items:
          - hash: LW5oTV9pmpX7+xWMjgC3IgbHtLkSMlCgyaKXG13CihA=
            key: admission-config-psact
            path: /etc/rancher/rke2/config/rancher-psact.yaml
          name: molmedocis-admission-configuration-psact
      machineLabelSelector:
        matchLabels:
          rke.cattle.io/control-plane-role: "true" (edited)  
 ``` 
 - Re-edit a field on the cluster object to trigger cluster reconciliation again. 
 - A new `fileSource` gets added to the cluster object with duplicate values on every cluster update. 

### Expected Result
Only one unique `fileSource` is added to the `machineSelectorFiles` on cluster edits if the secret or the hash value doesn't change. 

SURE-9071
