### ISSUE TITLE
There is currently no method of setting the correct flannel plugin network options required for windows clusters

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/terraform-provider-rancher2#387]
The rancher2 tf provider doesn't properly configure the flannel plugin network options that are required for Windows clusters. This causes Windows worker nodes to end up in a broken state and the cluster has to be completely rebuilt and the correct config (included below) to be present at the time the cluster is built. This config is included in the cluster.yaml when the Windows Support boolean is set to Enabled via the Rancher UI. This config is not included when setting the windows_prefered_cluster boolean to true in the rancher2 TF provider.

```yaml
  network:
    mtu: 0
    options:
      flannel_backend_port: '4789'
      flannel_backend_type: vxlan
      flannel_backend_vni: '4096'
    plugin: flannel
  restore:
    restore: false
```

If the flannel plugin network options for Windows aren't present at the time of cluster creation, the flannel network will be broken between windows and Linux nodes. This is more than likely due to the difference in flannel ports used for Windows and Linux. Windows will try to talk using the flannel backend port 4789, while non-windows clusters use 8472 for flannel vxlan overlay networking. There is no way to modify these values after the cluster is created.

source: https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ports/#other-port-considerations 

```
UDP | 8472 | Canal/Flannel VXLAN overlay networking
-- | -- | --
UDP | 4789 | Flannel VXLAN overlay networking on Windows cluster
```
