### ISSUE TITLE
rancher2_namespace create some annotations by default without commit to terraform state.

### ISSUE THREAD

**Issue by hanyouqing** [rancher/terraform-provider-rancher2#422]
I created my cluster and some resources with `terraform-provider-rancher2`, it seems that creates `namespace` with some `annotations` automatically like this:

```
metadata:
  annotations:
    cattle.io/status: '{"Conditions":[{"Type":"InitialRolesPopulated","Status":"True","Message":"","LastUpdateTime":"2020-06-04T04:36:28Z"},{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2020-06-04T04:36:27Z"}]}'
    field.cattle.io/containerDefaultResourceLimit: '{"limitsCpu":"100m","limitsMemory":"200Mi","requestsCpu":"50m","requestsMemory":"100Mi"}'
    field.cattle.io/creatorId: user-wj5rr
    field.cattle.io/description: staging namespace
    field.cattle.io/projectId: c-pszr4:p-9p6pd
    lifecycle.cattle.io/create.namespace-auth: "true"
  creationTimestamp: "2020-06-04T04:36:26Z"
```

 but it didn't commit the annotations into the terraform state when adding some new annotations to the tf files it said:

```
 ~ annotations      = {
     - "cattle.io/status"                          = jsonencode(
           {
             - Conditions = [
                 - {
                     - LastUpdateTime = "2020-06-17T11:16:52Z"
                     - Message        = ""
                     - Status         = "True"
                     - Type           = "InitialRolesPopulated"
                   },
                 - {
                     - LastUpdateTime = "2020-06-17T11:16:51Z"
                     - Message        = ""
                     - Status         = "True"
                     - Type           = "ResourceQuotaInit"
                   },
               ]
           }
       ) -> null
     + "iam.amazonaws.com/permitted"               = ".*"
     - "lifecycle.cattle.io/create.namespace-auth" = "true" -> null
```

it made me confused, and I don't know what will be affected by this.
anyone can help me or give some suggestions? can I just ignore this run apply directly?
