### ISSUE TITLE
Rancher2_app answer not possible with helm chart List parameter?

### ISSUE THREAD

**Issue by mueller-tobias** [rancher/terraform-provider-rancher2#433]
Hi,

i've a problem with deploying an app with a list parameter in the answer section, but the deployment fails everytime because the parameter is not generated properly. In YAML it would be the following code. When i deploy the App via YAML from rancher everything is working. But i can't build to correct ingress.hosts syntax to get the helm chart running.

``` yaml
server:
  # Resource requests, limits, etc. for the server cluster placement. This
  # should map directly to the value of the resources field for a PodSpec.
  # By default no direct resource request is made.

  # Ingress allows ingress services to be created to allow external access
  # from Kubernetes to access Vault pods.
  ingress:
    enabled: true
    hosts:
      - host: vault.demo.local
        paths:
          - /vault
```

No i've the problem to deploy that app via rancher2_app

``` hcl
resource "rancher2_app" "vault_work" {
  catalog_name     = "hashicorp"
  name             = "vault"
  description      = "Vault Workload Deployment"
  project_id       = data.rancher2_project.default.id
  template_name    = "vault"
  template_version = "0.7.0"
  target_namespace = rancher2_namespace.vault_work.name
  depends_on       = [rancher2_namespace.vault_work]
  answers = {
    "server.ha.enabled"                = "true"
    "server.ha.raft.enabled"           = "true"
    "server.dataStorage.size"          = "1Gi"
    "server.dataStorage.storageClass"  = "longhorn-single-node"
    "server.auditStorage.size"         = "1Gi"
    "server.auditStorage.storageClass" = "longhorn-single-node"
    "ui.enabled"                       = "true"
    "ui.serviceType"                   = "NodePort"
    "server.ingress.enabled" = "true"
    "server.ingress.enabled" = "true"
    "server.ingress.hosts.host" = "vault.mydomain.net"
    "server.ingress.hosts.host.paths" = "/vault"
  }
}
```
I always get the error: 
`Wait helm template failed. coalesce.go:195: warning: destination for hosts is a table. Ignoring non-table value [map[host:chart-example.local paths:[]]] Error: template: vault/templates/server-ingress.yaml:41:15: executing "vault/templates/server-ingress.yaml" at <.host>: can't evaluate field host in type interface {} Use --debug flag to render out invalid YAML : exit status 1`

Is there any possibility to use the answer Paramter to provide a list parameter to a helm chart?

### Versions
Rancher: 2.4.5
Helm Template: 0.7.0
Terraform: v0.13.0
Terraform Rancher2 Provider: rancher/rancher2 v1.10.0
