### ISSUE TITLE
rancher2_app_v2 values yaml syntax

### ISSUE THREAD

**Issue by mikekuzak** [rancher/terraform-provider-rancher2#534]
Hi,

I can't find any documentation how to add a scan to the new cis benchmark via the app-v2 resource. 
There is a value files which can take a yaml but there is also no documentation of the syntax for this. 

I tried this: 
```
resource "rancher2_app_v2" "rancher-cis-benchmark" {  
  cluster_id = "&lt;CLUSTER_ID&gt;"
  name = "rancher-cis-benchmark"
  namespace = "istio-system"
  repo_name = "rancher-charts"
  chart_name = "rancher-cis-benchmark"
  chart_version = "1.0.100"
 value = file(cis.yaml) 
 wait = true
}
```
```
cis.yaml
spec:
  scanProfileName: rke-profile-permissive
```

but no luck.

**Comment by rawmind0** [comment]
Hi @mikekuzak ,  one thing are the supported values of `rancher-cis-benchmark` chart (App v2) and another one is the execution of a cluster scan. 

To be able to cis scan your cluster you need to deploy the App first, `rancher-cis-benchmark` supported chart values
```
affinity: {}
global:
  cattle:
    systemDefaultRegistry: ''
  kubectl:
    repository: rancher/kubectl
    tag: v1.18.6
image:
  cisoperator:
    repository: rancher/cis-operator
    tag: v1.0.1
  securityScan:
    repository: rancher/security-scan
    tag: v0.2.1
  sonobuoy:
    repository: rancher/sonobuoy-sonobuoy
    tag: v0.16.3
nodeSelector: {}
resources: {}
tolerations: []
```

CIS cluster scan is not yet supported at this provider. We are working on it and should be available pretty soon.
