### ISSUE TITLE
1.16.0 - event_rate_limit error - converting YAML to JSON: yaml: line 4: did not find expected key

### ISSUE THREAD

**Issue by ifelsefi** [rancher/terraform-provider-rancher2#713]
Hi

My config uses [event rate](https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/cluster#event_rate_limit) limit example from your documentation:

``` services {
      etcd {
        creation = "6h"
        retention = "24h"
        uid = "499"
        gid = "499"
        snapshot = "false"
        extra_args = { "election-timeout":  "5000", "heartbeat-interval" : "500" }
        }
      kube_api {
        service_cluster_ip_range = "172.30.0.0/16"
        service_node_port_range = "30000-32767"
        always_pull_images = "false"
        audit_log {
          enabled = "true"
        }
        event_rate_limit {
          configuration = "apiVersion: eventratelimit.admission.k8s.io/v1alpha1\nkind: Configuration\nlimits:\n- type: Server\n burst: 35000\n qps: 6000\n"
          enabled = "true"
        }
      }
```

Though that gives an error:

```
[~/repos/terraform_rancher]$ terraform apply
╷
│ Error: "rke_config.0.services.0.kube_api.0.event_rate_limit.0.configuration" must be in yaml format, error: error converting YAML to JSON: yaml: line 4: did not find expected key
│
│   with rancher2_cluster.kafka,
│   on kafka.tf line 15, in resource "rancher2_cluster" "kafka":
│   15: resource "rancher2_cluster" "kafka" {
```

If I run with echo we see the issue as we `need another space` in front of burst and qps:

```
[~/repos/terraform_rancher]$ echo -e "apiVersion: eventratelimit.admission.k8s.io/v1alpha1\nkind: Configuration\nlimits:\n- type: Server\n burst: 35000\n qps: 6000\n"
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
- type: Server
 burst: 35000
 qps: 6000
 
 ```
 
 So use the below where asterisks show the number of spaces present.

`configuration*=*"apiVersion:*eventratelimit.admission.k8s.io/v1alpha1\nkind:*Configuration\nlimits:\n-*type:*Server\n**burst:*35000\n**qps:*6000\n"`

Which gives:

```
[~/repos/terraform_rancher]$ echo -e "apiVersion: eventratelimit.admission.k8s.io/v1alpha1\nkind: Configuration\nlimits:\n- type: Server\n  burst: 35000\n  qps: 6000\n"
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
- type: Server
  burst: 35000
  qps: 6000
  
```  
  
The documentation may want to be updated with this corrected example.
