### ISSUE TITLE
How to close the gap server creation and bootstrapping with password

### ISSUE THREAD

**Issue by exocode** [rancher/terraform-provider-rancher2#781]
I have created a Rancher 2.6.x server successfully via Terraform and in a Docker environment. How can I close the gap getting the `initial_password` and handle it over to the `rancher2_bootstrap`?

Yes, I can grep the password running: 

`docker logs CONTAINER_ID 2>&1 | grep "Bootstrap Password:"`

But how to handle over that one, to prevent a second `terraform apply`-command?
At the moment I do a `terraform apply` wait it's built, than grep the password and insert it manually into the same file and run `terraform apply` again :-(. 

That feels not right. I wanna get that working in one swipe **without manual steps**.

Does anyone has an idea go close that gap? 
(I am quite new to Terraform)

Thank you in advance 

That is the code I bootstrap Rancher: 

```terraform
provider "rancher2" {
  alias     = "bootstrap"
  timeout   = "240s"
  api_url   = "https://${var.rancher_hostname}"
  bootstrap = true
}

# Provider config for admin
provider "rancher2" {
  alias = "admin"

  api_url   = rancher2_bootstrap.admin.url
  token_key = rancher2_bootstrap.admin.token
  insecure  = true
}

resource "rancher2_bootstrap" "admin" {
  provider         = rancher2.bootstrap
  initial_password = THE_PASSWORD_FROM_INSTALLATION_SHOULD_GO_HERE
  password         = var.rancher_password
  telemetry        = true
}

output "bootstrap" {
  value = [
    rancher2_bootstrap.admin
  ]
}
```

**Comment by rawmind0** [comment]
As explained at docs, https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/bootstrap, you have the option to set any initial password during the Rancher 2.6.x deployment, so you could set it as `initial_password` argument

**Comment by exocode** [comment]
Hi @rawmind0,
Thank you for your attention

I definitly doing something wrong:

I already tried to set that `initial_password`:

```tf
  initial_password = var.rancher_password
  password         = var.rancher_password
```
BTW: when I set `initial_password` value to the password in the Rancher logs (`docker logs  container-id  2>&1 | grep "Bootstrap Password:"`) in the second run it works (terraform apply does not fail)

  I get these logs:

```shell
module.rancher_server.rancher2_bootstrap.admin: Still creating... [3m40s elapsed]
module.rancher_server.rancher2_bootstrap.admin: Still creating... [3m50s elapsed]
module.rancher_server.rancher2_bootstrap.admin: Still creating... [4m0s elapsed]
2021/10/20 17:27:26 [DEBUG] POST https://gitlab.com/api/v4/projects/XXXXXX/terraform/state/default?ID=141786ef-cb30-d427-7aca-ed471c59f7bf
╷
│ Error: [ERROR] Timeout trying to login with admin user: Doing  user logging: error Unauthorized
│ 
│   with module.rancher_server.rancher2_bootstrap.admin,
│   on modules/rancher/main.tf line 87, in resource "rancher2_bootstrap" "admin":
│   87: resource "rancher2_bootstrap" "admin" {
│ 
╵
2021/10/20 17:27:27 [DEBUG] DELETE https://gitlab.com/api/v4/projects/XXXXXX/terraform/state/default/lock
```

But at this moment, Rancher was already deployed through a Docker installation. I did this via a `cloud_init` script, where I tried to provide an `ENV` var:

`export CATTLE_BOOTSTRAP_PASSWORD=${rancher_password}`

How else shoudl I deploy Rancher, if not already a cluster is running, except through Docker?

Here is the script for completion (it runs before
```yaml 
#cloud-config
ssh_authorized_keys:
  - ${ssh_authorized_key}

package_update: true
package_upgrade: true

write_files:
  - path: /opt/docker-compose.yml
    content: |
      version: '2'
      services:
        rancher-server:
          privileged: true
          image: rancher/rancher:stable
          command: --acme-domain ${rancher_hostname}
          restart: unless-stopped
          volumes:
          - ./data/rancher:/var/lib/rancher
          ports:
          - 80:80
          - 443:443
  - path: /etc/systemd/system/rancher_server.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Rancher Server
      After=network.target docker.service
      [Service]
      Restart=always
      ExecStartPre=/usr/bin/docker-compose -f '/opt/docker-compose.yml' down -v
      ExecStartPre=/usr/bin/docker-compose -f '/opt/docker-compose.yml' rm -fv
      ExecStart=/usr/bin/docker-compose --file '/opt/docker-compose.yml' -p rancher_server up -d
      ExecStop=/usr/bin/docker-compose -f '/opt/docker-compose.yml' down -v

      [Install]
      WantedBy=multi-user.target
runcmd:
  - ["export CATTLE_BOOTSTRAP_PASSWORD=${rancher_password}"]
  - [
      sh,
      -c,
      "sudo apt install -y apt-transport-https ca-certificates curl gnupg lsb-release",
    ]
  - [
      sh,
      -c,
      "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg",
    ]
  - [
      sh,
      -c,
      'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null',
    ]
  - [sh, -c, "sudo apt-get update"]
  - [sh, -c, "sudo apt-get install -y docker-ce docker-ce-cli containerd.io"]
  - [sh, -c, "sudo apt install -y docker-compose"]
  - [sh, -c, "sudo service docker start"]
  - systemctl daemon-reload
  - systemctl enable rancher_server.service
  - systemctl start rancher_server.service

```
