### ISSUE TITLE
rancher2_app_v2 values not passed to sub charts (part 2)

### ISSUE THREAD

**Issue by Sartigan** [rancher/terraform-provider-rancher2#813]
I don't know if it is similar to: https://github.com/rancher/terraform-provider-rancher2/issues/545 Everything but the "global" section is passed to the app_v2 values.

**Provider version:** rancher/rancher2 v1.21.0
**Terraform Version:** 1.0.0

```
  + resource "rancher2_app_v2" "rancher_monitoring" {
      + annotations                 = (known after apply)
      + chart_name                  = "rancher-monitoring"
      + chart_version               = "100.0.0+up16.6.0"
      + cleanup_on_fail             = false
      + cluster_id                  = "local"
      + cluster_name                = (known after apply)
      + disable_hooks               = false
      + disable_open_api_validation = false
      + force_upgrade               = false
      + id                          = (known after apply)
      + labels                      = (known after apply)
      + name                        = "rancher-monitoring"
      + namespace                   = "cattle-monitoring-system"
      + project_id                  = "local:p-wrz89"
      + repo_name                   = "rancher-charts"
      + system_default_registry     = (known after apply)
      + values                      = <<-EOT
            defaultRules:
              create: false
              labels:
                severity: warning
            global:
              cattle:
                clusterId: local
                clusterName: local
                systemDefaultRegistry: nexus3.com
        EOT
```

When I check the values.yaml from the app:

```
global:
  cattle:
    systemDefaultRegistry: ''
    windows:
      enabled: false
  imagePullSecrets: []
  kubectl:
    pullPolicy: IfNotPresent
    repository: rancher/kubectl
    tag: v1.20.2
  rbac:
    create: true
    pspAnnotations: {}
    pspEnabled: true
    userRoles:
      aggregateToDefaultRoles: true
      create: true
```

It is like the `global` section is ignored
