### ISSUE TITLE
All nodes are added to the external load balancer backend pool regardless of their type [downstream RKE cluster in Azure using node templates/pools]

### ISSUE THREAD

**Issue by tuxicorn** [rancher/terraform-provider-rancher2#974]
When I create an RKE cluster with an external Load Balancer on Azure it automatically adds all nodes to the Load Balancer backend pool, I should be able to choose which nodes are added (only Worker or only the Control Plane nodes) and I haven't been able to find any documentation for that.

### Requirements

| Name     | Version |
| ----------- | ----------- |
| terraform   | 1.2.6       |
| rancher/rancher2  provider | 1.24.0  |
| kubernetes | 1.23.8 |
| rancher | 2.6.6 |

### Cluster nodes
![Screenshot from 2022-08-17 15-31-50](https://user-images.githubusercontent.com/66470559/185147004-ab323708-43fb-4f91-b28b-ba1eab394b16.png)

### Load Balancer Backend pool
![Screenshot from 2022-08-17 15-27-59](https://user-images.githubusercontent.com/66470559/185147052-301401cb-358f-4bef-aaca-0917cb2563e1.png)

### Addon used for creating the external load balancer
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
 ```
